a={1,2,4,8,9,3,7,2,1,1,1}
print(a)
print("The length of th set a is :")
print(len(a))
b={1,2,4,20,15,5}
print(b)
print("a union b is :")
print(a|b)
print("a intersection b is :")
print(a&b)
print("a difference b is")
print(a-b)
print("semantical diiference is")
print(a^b)
print("a union b is :")
print(a.union(b))
print("a intersection b is :")
print(a.intersection(b))
print("a difference b is")
print(a.difference(b))

